ALTER TABLE ACT_ID_MEMBERSHIP
DROP CONSTRAINT ACT_FK_MEMB_GROUP;

ALTER TABLE ACT_ID_MEMBERSHIP
DROP CONSTRAINT ACT_FK_MEMB_USER;

DROP TABLE IF EXISTS ACT_ID_INFO;
DROP TABLE IF EXISTS ACT_ID_MEMBERSHIP;
DROP TABLE IF EXISTS ACT_ID_GROUP;
DROP TABLE IF EXISTS ACT_ID_USER;